DROP TRIGGER IF EXISTS `yuriichuk_7_72`.`users_BEFORE_DELETE`;

DELIMITER $$
USE `yuriichuk_7_72`$$
CREATE DEFINER = CURRENT_USER TRIGGER `yuriichuk_7_72`.`users_BEFORE_DELETE`
BEFORE DELETE ON `users`
FOR EACH ROW
BEGIN
	IF old.id IN (SELECT user_id FROM bookmark) THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = "FK constraint. User is referenced.";
    END IF;
END$$
DELIMITER ;
